In [16]:
import numpy as mp

In [23]:
mp.random.seed(12)
arr = mp.random.randint(1,20,12).reshape(4,-1)


In [24]:
print(arr)

[[12  7 18]
 [ 3  4  4]
 [13 17 18]
 [ 6 14  3]]


In [25]:
arr>5

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True, False]])

In [26]:
arr[arr%2==0] = 0   # if we change number it  global change

In [27]:
arr

array([[ 0,  7,  0],
       [ 3,  0,  0],
       [13, 17,  0],
       [ 0,  0,  3]])