In [1]:
import numpy as np


In [2]:
np.random.seed(123)
arr1 = np.random.randint(1,20,9).reshape(3,-1)
arr2 = np.random.randint(20,40,9).reshape(3,-1)

In [4]:
print(arr1)

[[14  3  3]
 [ 7 18 11]
 [ 2  1 18]]


In [5]:
 print(arr2)

[[35 29 20]
 [34 20 35]
 [39 34 24]]


In [27]:
np.hstack((arr1,arr2)) # horizontal staking bewtween array 

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [28]:
np.vstack((arr1,arr2)) # vetical staking between array 

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [29]:
np.vstack((arr1,arr2)).size #  find size 

18

In [30]:
np.vstack((arr1,arr2)).ndim # find dimensions 

2

In [31]:
m1  = np.random.randint(1,10,4)
m2 = np.random.randint(11,20,4)

In [32]:
m1

array([8, 3, 5, 9])

In [33]:
m2

array([11, 18, 14, 15])

In [35]:
np.vstack((m1,m2))  # vertical stake using array 

array([[ 8,  3,  5,  9],
       [11, 18, 14, 15]])