# Numerical operation of  Two  array 


In [20]:
import numpy as np

In [21]:
arr1 = np.arange(1,10)
arr2 = np.arange(11,20)

In [22]:
print(arr1,arr2,sep= "\n")

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [23]:
arr3 = arr1 +arr2

In [24]:
print(arr3)

[12 14 16 18 20 22 24 26 28]


In [25]:
arr1 = arr1.reshape(3,-1)
arr2 = arr2.reshape(3,-1)

In [26]:
print("arr1 =" , arr1,sep = "\n")
print("arr2 =" , arr2,sep = "\n")

arr1 =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2 =
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [27]:
arr1+arr2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [28]:
arr1.dot(arr2) # this function for matix multipication 

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])