In [1]:
import numpy as np


In [19]:
np.random.seed(123)
matrix = np.random.randint(1,11,9).reshape(3,-1)

In [20]:
print(matrix)

[[ 3  3  7]
 [ 2  4 10]
 [ 7  2  1]]


In [21]:
matrix.max() # find max number 

10

In [22]:
matrix.sum() # find sum of matrix 

39

In [23]:
matrix.min() # find minmum number in matrix 

1

In [24]:
matrix.argmax() # find maximum index 

5

find minum in each row 


for row = 1 & column = 0  

In [28]:
print(matrix)

[[ 3  3  7]
 [ 2  4 10]
 [ 7  2  1]]


In [30]:
np.sum(matrix,axis = 0 )   # sum of every column 

array([12,  9, 18])

In [31]:
np.sum(matrix,axis = 1 ) # sum of every row 

array([13, 16, 10])

In [33]:
np.cumsum(matrix)  # cumulative sum of matrix


array([ 3,  6, 13, 15, 19, 29, 36, 38, 39])

In [36]:
np.cumsum(matrix , axis = 1 ) # row wise cumulative sum of matrix  

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]])

In [37]:
np.cumsum(matrix , axis = 0 ) # column  wise cumulative sum of matrix  

array([[ 3,  3,  7],
       [ 5,  7, 17],
       [12,  9, 18]])

In [39]:
np.prod(matrix)  # total product of every term
 

70560

In [40]:
np.prod(matrix,axis = 1 ) # column wise product 

array([63, 80, 14])

In [41]:
np.prod(matrix , axis = 0 ) # procudt wise product 

array([42, 24, 70])

In [43]:
np.mean(matrix)   # mean of matrix 

4.333333333333333

In [44]:
np.mean(matrix, axis = 0 )   # row wise mean 

array([4., 3., 6.])

In [45]:
np.mean(matrix,axis = 1 )  # mean of column 

array([4.33333333, 5.33333333, 3.33333333])