# import Numpy library

In [1]:
import numpy as np

# Create an array using array function 

In [3]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##  Create an array containing numbers form 20 to 40  

In [7]:
arr = np.random.randint(20,41,10)

In [8]:
arr

array([27, 26, 23, 25, 34, 24, 39, 31, 25, 28])

### Create an Array which contain 10 elements and every element is 5 

In [15]:
arr = np.array([5 for i in range(10)])

In [16]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### Create array containing 20 random interger every even number with -1  

In [24]:
 arr = np.random.randint(1,100,20)

In [25]:
arr

array([73, 75, 94,  7, 70,  8,  8, 65, 16, 77, 43, 22, 17, 88, 57, 21, 44,
       63, 65, 25])

In [26]:
arr[arr%2 == 0 ] = -1

In [27]:
arr

array([73, 75, -1,  7, -1, -1, -1, 65, -1, 77, 43, -1, 17, -1, 57, 21, -1,
       63, 65, 25])

### Stake to 2d  arary 

In [28]:
m1 = np.random.randint(1,110,9).reshape(3,3)
m2 = np.random.randint(110,210,9).reshape(3,3)


In [29]:
m1

array([[96,  3, 56],
       [ 6,  6, 20],
       [37, 65, 39]])

In [30]:
m2

array([[174, 208, 158],
       [203, 168, 209],
       [176, 122, 133]])

In [31]:
np.hstack((m1,m2))

array([[ 96,   3,  56, 174, 208, 158],
       [  6,   6,  20, 203, 168, 209],
       [ 37,  65,  39, 176, 122, 133]])

In [32]:
np.vstack((m1,m2))

array([[ 96,   3,  56],
       [  6,   6,  20],
       [ 37,  65,  39],
       [174, 208, 158],
       [203, 168, 209],
       [176, 122, 133]])