# Reshape of numpy


In [8]:
import numpy as np


In [9]:
arr = np.random.randint(2,20,10)

In [10]:
arr

array([17, 13,  4,  5, 16,  8,  2,  5, 15, 12])

In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
arr.shape

(10,)

In [13]:
arr2 = arr.reshape(2,5)  # argument multiply is equal to no of variable other give a error


In [14]:
arr2 
arr.ndim
arr.shape

(10,)

In [15]:
arr2

array([[17, 13,  4,  5, 16],
       [ 8,  2,  5, 15, 12]])

In [16]:
arr2.ndim

2

In [17]:
ar_t = np.arange(0,50)
ar_t  # arrange functin can take input in a certain limit form first argument to last argument 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
ar = ar_t.reshape(5,-1) # -1 indiccae he own calculate it is run for who many term are need 
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [19]:
ar2 = ar_t.reshape(-1,5)
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [20]:
np.random.seed(12) #Setting a seed using the seed function allows you to reproduce the same sequence of random numbers every time you run your program. 
re = np.random.randint(2,20,10)
re

array([13,  8, 19,  4,  5,  5, 14, 18, 19,  7])

In [21]:
r = re.reshape(2,-1)
r

array([[13,  8, 19,  4,  5],
       [ 5, 14, 18, 19,  7]])