In [7]:
import numpy as np 


In [8]:
np.random.seed(123)
matrix = np.random.randint(1,15,15)

In [9]:
matrix

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [10]:
np.random.shuffle(matrix)

In [11]:
matrix

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [13]:
np.unique(matrix)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [14]:
matrix

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [20]:
np.unique(matrix, return_counts = True,return_index = True) # return counts give how many time they present 
# return_index give the index of element of array 

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14], dtype=int64),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1], dtype=int64))