In [2]:
import numpy as np

In [3]:
arr = np.array([9,2,3,4,5,49,32])

In [4]:
print(arr)

[ 9  2  3  4  5 49 32]


In [5]:
np.min(arr) # find minimum number 

2

In [6]:
np.max(arr) # find max number in array

49

In [7]:
np.argmin(arr)  # find index of minmun number in array 

1

In [8]:
np.argmax(arr) # find index of maximum number n array  & index start in 0 

5

In [9]:
arr1 = np.array([[1,2,3],[5,10,7],[7,8,9]])

In [10]:
print(arr1)

[[ 1  2  3]
 [ 5 10  7]
 [ 7  8  9]]


In [11]:
np.argmax(arr1)

4

In [12]:
np.sqrt(arr) 
# find square root in array 

array([3.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       7.        , 5.65685425])

In [13]:
np.exp(arr)   # expontional number 

array([8.10308393e+03, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 1.90734657e+21, 7.89629602e+13])

In [14]:
np.cos(arr) # find cos value in array 

array([-0.91113026, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.30059254,  0.83422336])

In [15]:
np.sin(arr) # find sine value in array 

array([ 0.41211849,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.95375265,  0.55142668])

In [16]:
np.tan(arr)  # find tan value in arary 

array([-0.45231566, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -3.17290855,  0.66100604])

In [17]:
np.linspace(0,50,5) # find 5 number between 0 10 50 in same difference 

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [18]:
np.array([1,2,4,0,32,0 ],dtype="bool")  # creat bool array non zerore value to be true 

array([ True,  True,  True, False,  True, False])

In [24]:
arr1

array([[ 1,  2,  3],
       [ 5, 10,  7],
       [ 7,  8,  9]])

In [28]:
print(np.sort(arr1)) # storting using array 

[[ 1  2  3]
 [ 5  7 10]
 [ 7  8  9]]
