# This is heading 
#       our code 


In [3]:
print("Hello World ")

Hello World 


In [4]:
import numpy as np

In [41]:
num =[ [[1,2,3],[4,5,6],[5,6,7] ], [[1,2,3],[4,5,6.0],[5,6,7] ]]

In [42]:
nums = np.array(num)

In [43]:
nums

array([[[1., 2., 3.],
        [4., 5., 6.],
        [5., 6., 7.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [5., 6., 7.]]])

In [44]:
nums.ndim


3

In [45]:
nums.shape

(2, 3, 3)

In [46]:
nums.dtype

dtype('float64')

eye, ones , zeroes , dias 

In [56]:
n1 = np.ones(3)          
n1
            

array([1., 1., 1.])

In [53]:
n2= np.zeros(2)
n2

array([0., 0.])

In [59]:
n2 = np.ones((2,3))
n2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
n3 = np.eye(4)
n3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
n3 = np.eye(4,3)
n3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [68]:
n4 = np.diag([4,8,9,98])
n4

array([[ 4,  0,  0,  0],
       [ 0,  8,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 98]])

In [69]:
n4 = np.diag(n4)
n4

array([ 4,  8,  9, 98])

In [209]:
ran_arr = np.random.randint(1,20,5) # first for start , ending , how many number are input 
ran_arr

array([ 8, 16,  5, 16,  4])

In [213]:
rand_ar = np.random.rand(3,3) # find flat number between 0 to 1 
rand_ar

array([[0.06157686, 0.96382933, 0.83579735],
       [0.71219795, 0.94603366, 0.59215519],
       [0.29280163, 0.58482924, 0.82471108]])

In [215]:
rand_ar = np.random.randn(3,3) # find flat number between nearest to 0 -ve and +ve both 
rand_ar

array([[-0.25457236, -0.5101029 , -0.80529977],
       [-1.96578933,  0.29530881,  0.04667666],
       [ 0.96446724, -0.98693883,  1.35569519]])

In [216]:
np


<module 'numpy' from 'C:\\Users\\amitk\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>